### ISSUE TITLE
Problem with database.yml

### ISSUE THREAD

**Issue by moazkh60** [reddimohan/flask-rest-api-barebones-with-authentication#1]
please add an example yml file it's showing a lot of errors

**Comment by reddimohan** [comment]
> please add an example yml file it's showing a lot of errors

Hello @moazkh60 ,

database.yml_sample file is already present in the main folder (main/database.yml_sample) and I have updated documentation also on how to use that. please refer 7th point from the README.

Thanks,
MO

**Comment by reddimohan** [comment]
closed this issue for inactivity
